### ISSUE TITLE
你好，问一下为啥这个BOSS状态更新，2分钟就发一次

### ISSUE THREAD

**Issue by yantaibimo** [yoooowi/pcr_autocb#10]
你好，问一下为啥这个BOSS状态更新，2分钟就发一次，
![image](https://user-images.githubusercontent.com/82109776/147694411-754cb249-74a7-498e-9178-c2435d0af932.png)
这个频率有没有办法能调低点

**Comment by yoooowi** [comment]
数据库没有初始化造成的。确保你pull的是最新的版本，发送`init@bot`初始化。

**Comment by yantaibimo** [comment]
> 数据库没有初始化造成的。确保你pull的是最新的版本，发送初始化。`init@bot`

行了，感谢
