### ISSUE TITLE
这期还能正常使用吗？

### ISSUE THREAD

**Issue by XiaoFuOS** [yoooowi/pcr_autocb#18]
我的突然没反应了，本插件所有指令都是，其他插件正常使用，不会是风控的原因

**Comment by yoooowi** [comment]
我的还能用。能看看log吗

**Comment by XiaoFuOS** [comment]
![QQ截图20220625134718](https://user-images.githubusercontent.com/103229747/175760232-9222e1c5-5ed5-4463-bba2-fcc34e2c4be3.png)
三种init都没反应，api和群号都设置了，模块也加了

**Comment by yoooowi** [comment]
![pic1](https://user-images.githubusercontent.com/67884123/175760372-8dc6638c-3102-4001-8316-3ccd6761a5af.png)

正常情况下收到指令至少应该会有两个log，一个显示收到消息，另一个显示触发指令。

重启bot的时候log应该有很多`INFO: Succeeded to import XXXXX`，你看看 autocb 在不在里面？

**Comment by XiaoFuOS** [comment]
![QQ截图20220625140145](https://user-images.githubusercontent.com/103229747/175760678-54320f41-f1b0-4b3d-8449-0e201d60a74e.png)
只有dao正常吗

**Comment by yoooowi** [comment]
上面一行写了 cannot import MessageSegment from hoshino，就是没有成功启动的原因。你是更新了hoshinobot或者nonebot什么的吗？

**Comment by XiaoFuOS** [comment]
hoshinobot用的github里最新的，难不成结构发生了变化

**Comment by XiaoFuOS** [comment]
> hoshinobot用的github里最新的，难不成结构发生了变化

然后就是其他插件能正常使用

**Comment by yoooowi** [comment]
作者在 https://github.com/Ice-Cirno/HoshinoBot/commit/fb630760a88b4590c076d7b737e7d98eb664d76a 这个commit里改变了结构， 将
```python
from nonebot import Message, MessageSegment, message_preprocessor
```
改为了
```python
from nonebot import message_preprocessor
```
估计是导致问题的原因。试试看把这一行复原能不能解决问题。

**Comment by yoooowi** [comment]
文件是 [HoshinoBot](https://github.com/Ice-Cirno/HoshinoBot)/[hoshino](https://github.com/Ice-Cirno/HoshinoBot/tree/master/hoshino)/__init__.py

**Comment by XiaoFuOS** [comment]
> 

你这个是解决了，可以了，正常使用，就是不知道其他插件会不会受到影响，先使用看看吧，谢谢你

**Comment by daseinem** [comment]
也可以改成直接从nonebot导入MessageSegment ([cbsimple.py](https://github.com/yoooowi/pcr_autocb/blob/master/cbsimple.py)):
```
from hoshino import HoshinoBot, Service, util, priv, MessageSegment
```
->
```
from hoshino import HoshinoBot, Service, util, priv
from nonebot import MessageSegment
```
