### ISSUE TITLE
没有办法显示当前boss为几王

### ISSUE THREAD

**Issue by 253936563** [yoooowi/pcr_autocb#8]
![image](https://user-images.githubusercontent.com/17465843/147376024-1f112cfe-7ad5-4d93-8b65-a4082ffa91a4.png)

**Comment by 253936563** [comment]
没事了 是config.json boss名字写错了

**Comment by yoooowi** [comment]
明天测试完后会更新一个自动获取boss列表的功能 没问题的话以后不用手动设置config.json了

**Comment by 253936563** [comment]
> 明天测试完后会更新一个自动获取boss列表的功能 没问题的话以后不用手动设置config.json了

好的 谢谢。
